name : Run each pytest found

on   : [push]

jobs :
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.5", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pytest
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pytest
    - name: Run pytest recursively
      run: |
        ls -1d day?? | while read dir; do (cd $dir && pytest); done